# -*- coding: utf-8 -*-
"""ui

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1papd4IBOHxK5oHNtmjk3cF1Y-nL-_Nhb
"""

import gradio as gr
from app import run_pipeline

DESIGN_CHOICES = ["nudes", "french", "art", "ombre", "glitter"]

def gradio_predict(img, design_filter):
    allowed = design_filter if design_filter else None
    yolo_img, mask_img, html, overlay_img = run_pipeline(img, allowed_designs=allowed)
    return yolo_img, mask_img, overlay_img, html

with gr.Blocks() as demo:
    gr.Markdown("## 💅 Nail Shape & Design Recommender + Nail Overlay Preview")

    with gr.Row():
        with gr.Column():
            img_in = gr.Image(type="pil", label="손 이미지 업로드")
            design_filter = gr.CheckboxGroup(
                DESIGN_CHOICES,
                label="디자인 타입 필터 (선택 안 하면 전체)",
            )
            run_btn = gr.Button("네일 추천 실행")

        with gr.Column():
            yolo_out = gr.Image(type="pil", label="① YOLOv11 손톱 감지 결과")
            mask_out = gr.Image(type="pil", label="② SAM-HQ 마스크 시각화")
            overlay_out = gr.Image(type="pil", label="③ TOP2 네일 합성 결과")
            html_out = gr.HTML(label="④ 추천 결과 (TOP3)")

    run_btn.click(
        fn=gradio_predict,
        inputs=[img_in, design_filter],
        outputs=[yolo_out, mask_out, overlay_out, html_out],
    )


demo   # launch()는 colab에서 실행